### ISSUE TITLE
a config error about tokenizer

### ISSUE THREAD

**Issue by Chunchunwumu** [zhaowc-ustc/TabPedia-Towards-Comprehensive-Visual-Table-Understanding-with-Concept-Synergy#1]
I have setting the config file as the readme file.
but there is a error when load tokenizer, as shown in the figure. 
So I cann't inference with your pretrained weight.
Can you help to fix this bug?

![3e99329501cbd5510383570e84ca379](https://github.com/user-attachments/assets/32d1f432-de93-4cbd-9c0c-34fb9d4e3697)

![9b483feeb50dfd4dda713599a4659a2](https://github.com/user-attachments/assets/baf507f5-db74-4f90-9e17-bc24c02c1e93)

**Comment by zhaowc-ustc** [comment]
Could you provide the local folder path of "pretrained.pth" ?
