### ISSUE TITLE
fatal: Remote branch 9bce7b not found in upstream origin

### ISSUE THREAD

**Issue by LOVEISI** [zhaowc-ustc/TabPedia-Towards-Comprehensive-Visual-Table-Understanding-with-Concept-Synergy#2]
![image](https://github.com/user-attachments/assets/d1aba27f-0ec4-4c1b-a51d-4119930bfba6)
After writing git clone https://github.com/InternLM/xtuner.git -b 9bce7b ,it turns wrong.
Can you help me ?

**Comment by zhaowc-ustc** [comment]
Please utilize the following command: git clone https://github.com/InternLM/xtuner.git -b v0.1.15
We have updated the Readme.md file~

**Comment by LOVEISI** [comment]
ok,谢谢！
