### ISSUE TITLE
a config error about tokenizer

### ISSUE THREAD

**Issue by bang123-box** [zhaowc-ustc/TabPedia-Towards-Comprehensive-Visual-Table-Understanding-with-Concept-Synergy#3]
I have setting the config file as the readme file.
but there is a error when load tokenizer, as shown in the figure.
So I cann't inference with your pretrained weight.
Can you help to fix this bug? this question is same to [#1](https://github.com/zhaowc-ustc/TabPedia/issues/1)
![image](https://github.com/user-attachments/assets/0462c843-f132-4962-807e-5d3727bfc7eb)
![image](https://github.com/user-attachments/assets/53eb6d31-6590-4cc9-b87a-f2ab4fc7151c)
I find in your tabpedia dir, there is only pretrained.pth in there?

**Comment by zhaowc-ustc** [comment]
the config "llm_name_or_path" should be replaced with the path of "Your_Download_InternLM-7B-chat", not the "pretrained_pth/TabPedia/pretrained.pth"
<img width="534" alt="截屏2024-10-13 下午8 53 24" src="https://github.com/user-attachments/assets/a127d898-fea8-44d9-819d-4a2c47c4a0dd">

**Comment by bang123-box** [comment]
thk you much, very happy to help me solve it
